# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferreted_away', '0003_auto_20170320_1301'),
        ('ferreted_away', '0003_auto_20170320_1327'),
    ]

    operations = [
    ]
