# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreted_away', '0004_merge_20170320_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='other/placeholder.png', upload_to='profile_images'),
        ),
    ]
